"""add duplicate_of_id to articles

Revision ID: 3096aefcac34
Revises: db29c07d6a9b
Create Date: 2026-09-10 22:39:41.578286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3096aefcac34'
down_revision: Union[str, Sequence[str], None] = 'db29c07d6a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'articles', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'duplicate_of_id')
    # ### end Alembic commands ###
